# Generated by Django 6.0 on 2025-12-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Milvus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='basehtmltomarkdownconversion',
            name='batch_id_idx_1',
        ),
        migrations.RemoveIndex(
            model_name='basehtmltomarkdownconversion',
            name='batch_visitor_idx_1',
        ),
        migrations.RemoveIndex(
            model_name='basehtmltomarkdownconversion',
            name='scan_version_batch_idx_1',
        ),
        migrations.RemoveIndex(
            model_name='basehtmltomarkdownconversion',
            name='domain_cat_status_idx_1',
        ),
        migrations.RemoveIndex(
            model_name='basehtmltomarkdownconversion',
            name='batch_usr_uuid_idx2',
        ),
        migrations.RemoveIndex(
            model_name='basehtmltomarkdownconversion',
            name='usr_uuid_linkhash_html_idx',
        ),
        migrations.RemoveIndex(
            model_name='basehtmltomarkdownconversion',
            name='visitor_linkhash_html_idx',
        ),
        migrations.DeleteModel(
            name='BaseHtmlToMarkdownConversion',
        ),
    ]
