# Generated by Django 6.0 on 2025-12-23 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milvus', '0002_remove_basehtmltomarkdownconversion_batch_id_idx_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasedetails',
            name='json_ld_schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='BaseHtmlToMarkdownConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(blank=True, max_length=40, null=True)),
                ('project_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('task_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('scan_id', models.IntegerField(blank=True, null=True)),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.IntegerField()),
                ('markdown_total_summary_count', models.IntegerField(default=0)),
                ('markdown_conversion_url_count', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('include_parents_path', models.JSONField(blank=True, default=list)),
                ('domain', models.CharField(max_length=100)),
                ('exclude_parents_path', models.JSONField(blank=True, default=list)),
                ('include_url_hash_list', models.JSONField(blank=True, default=list)),
                ('exclude_url_hash_list', models.JSONField(blank=True, default=list)),
                ('is_others', models.BooleanField(default=False)),
                ('is_normal', models.BooleanField(default=False)),
                ('is_full_scan', models.BooleanField(default=False)),
                ('is_sitemap_collection', models.BooleanField(default=False)),
                ('onlyHtmlContent', models.BooleanField(default=False)),
                ('onlymainContent', models.BooleanField(default=False)),
                ('collection_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sitemap_xml_include_path', models.JSONField(blank=True, default=dict)),
                ('sitemap_xml_exclude_path', models.JSONField(blank=True, default=dict)),
                ('scan_status', models.CharField(max_length=50)),
                ('exclude_urls_count', models.IntegerField(default=0)),
                ('delayTimeInSec', models.IntegerField(default=2)),
                ('is_path_scan', models.BooleanField(default=False)),
                ('link_url_list', models.JSONField(blank=True, default=list, null=True)),
                ('credit_utilized', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_llm', models.BooleanField(default=False)),
                ('is_doc_gpt', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('total_batch_words', models.IntegerField(default=0)),
                ('total_batch_character', models.IntegerField(default=0)),
                ('total_batch_character_without_space', models.IntegerField(default=0)),
                ('batch_tokens', models.IntegerField(default=0)),
                ('total_rag_credits', models.IntegerField(blank=True, default=0, null=True)),
                ('schema', models.JSONField(blank=True, default=dict, null=True)),
                ('is_extension', models.BooleanField(default=False)),
                ('link_url_hash', models.CharField(blank=True, max_length=8, null=True)),
                ('cleaned_html', models.BooleanField(default=False)),
                ('is_non_html', models.BooleanField(default=False)),
                ('specific_ext', models.JSONField(blank=True, default=list)),
                ('enable_parallel', models.BooleanField(default=False)),
                ('parallel_workers', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'link_scrapper_app_basehtmltomarkdownconversion',
                'indexes': [models.Index(fields=['batch_id'], name='batch_id_idx_1'), models.Index(fields=['scan_id', 'version', 'batch_id'], name='scan_version_batch_idx_1'), models.Index(fields=['domain', 'category', 'scan_status'], name='domain_cat_status_idx_1'), models.Index(fields=['batch_id', 'user_uuid'], name='batch_usr_uuid_idx2'), models.Index(fields=['user_uuid', 'link_url_hash', 'cleaned_html'], name='usr_uuid_linkhash_html_idx')],
            },
        ),
    ]
