# Generated by Django 6.0 on 2025-12-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Milvus', '0003_knowledgebasedetails_json_ld_schema_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='htmltomarkdownconversion',
            unique_together=set(),
        ),
    ]
