# Generated by Django 6.0 on 2025-12-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milvus', '0004_alter_htmltomarkdownconversion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltomarkdownconversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
