# Generated by Django 6.0 on 2025-12-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milvus', '0005_alter_htmltomarkdownconversion_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltomarkdownconversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
