# Generated by Django 6.0 on 2025-12-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milvus', '0006_alter_htmltomarkdownconversion_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehtmltomarkdownconversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='basehtmltomarkdownconversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
